#
# This source file is part of the Spatial Continuity project
#
# SPDX-FileCopyrightText: 2025 Paul Heidekrüger 
#
# SPDX-License-Identifier: MIT
#

project: SpatialContinuity.xcodeproj
schemes:
- SpatialContinuityCamera
report_exclude:
- SpatialContinuityShared/**/*.swift
