#
# This source file is part of the Spatial Continuity project
#
# SPDX-FileCopyrightText: 2025 Paul Heidekrüger 
#
# SPDX-License-Identifier: MIT
#

project: SpatialContinuity.xcodeproj
schemes:
- SpatialContinuityCamera
- SpatialContinuity
report_exclude:
- SpatialContinuityShared/**/*.swift
# HACK: Is this the correct way to exclude external libraries from being checked?
- "**/*SpeziLLM*/**/*.swift"
disable_unused_import_analysis: true
relative_results: true
build_arguments:
- -skipPackagePluginValidation
- -skipMacroValidation
