#
# This source file is part of the Spatial Continuity project
#
# SPDX-FileCopyrightText: 2025 Paul Heidekrüger 
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  periphery:
    name: Periphery
    uses: StanfordBDHG/.github/.github/workflows/periphery.yml@v2
    permissions:
      contents: read
  # NOTE: CodeQL disabled until it supports the current Swift toolchain
  # codeql_scc:
  #   name: CodeQL Spatial Continuity Camera
  #   uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
  #   with:
  #     codeql: true
  #     fastlanelane: ios codeql_scc
  #   permissions:
  #     security-events: write
  #     actions: read
  # codeql_sc:
  #   name: CodeQL Spatial Continuity
  #   uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
  #   with:
  #     codeql: true
  #     fastlanelane: visionos codeql_sc
  #   permissions:
  #     security-events: write
  #     actions: read
  buildandtest_scc:
    name: Build Spatial Continuity Camera (for Testing)
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      fail-fast: false
      matrix:
        platform: [iphone]
    with:
      # We use the self-hosted runners as the main GitHub Action runners do not have the necessary performance.
      # Remove the `runsonlabels: '["macOS", "self-hosted"]'` lines if you do not administer your own GitHub Runners.
      runsonlabels: '["macOS", "self-hosted"]'
      fastlanelane: ios test_iphone # ${{ matrix.platform }}
      artifactname: ${{ matrix.platform }}.xcresult
  buildandtest_sc:
    name: Build Spatial Continuity (for Testing)
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      fail-fast: false
      matrix:
        platform: [VisionPro]
    with:
      # We use the self-hosted runners as the main GitHub Action runners do not have the necessary performance.
      # Remove the `runsonlabels: '["macOS", "self-hosted"]'` lines if you do not administer your own GitHub Runners.
      runsonlabels: '["macOS", "self-hosted"]'
      fastlanelane: visionos test_vision_pro # ${{ matrix.platform }}
      artifactname: ${{ matrix.platform }}.xcresult
  # NOTE: Disabled since no tests are being run ATM
  # uploadcoveragereport:
  #   name: Upload Coverage Report
  #   needs: [buildandtest]
  #   uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
  #   with:
  #     coveragereports: iphone.xcresult
  #   secrets:
  #     token: ${{ secrets.CODECOV_TOKEN }}
